### ISSUE TITLE
Mise en ligne des tutoriels

### ISSUE THREAD

**Issue by felixgirault** [DISIC/rgaa_bibliotheques_javascript#7]
Bonjour,

Existe-t-il une version en ligne des tutoriels ?
Il serait intéressant de pouvoir les consulter directement sans avoir à cloner le repo.

**Comment by Tobino** [comment]
La création d'une page projet github suffirait.
https://help.github.com/articles/creating-project-pages-manually/

Si la DISIC peut créer une branche `gh-pages`, je pourrais faire une pull request avec les modifications nécessaire.

**Comment by Tobino** [comment]
Ça sera plus simple que prévus.
Il suffit juste de créer la branche `gh-pages`

```
git checkout -b gh-pages
git push origin gh-pages
```

Puis la page sera disponible sous:
https://DISIC.github.io/rgaa_bibliotheques_javascript/tutoriels/index.html

Puis ajouter le lien dans le README de la master pour faciliter l'accès.

En attendant sur mon compte:
https://tobino.github.io/rgaa_bibliotheques_javascript/tutoriels/index.html

**Comment by sbonaventure** [comment]
:+1:

**Comment by philippeBron** [comment]
Merci pour cette proposition. J'avais effectivement dans l'idée de créer une gh-pages. J'ai découvert il y a peut cette fonctionnalité et me suis fait la main pendant les vacances avec celle du compte etat-plateforme (http://etat-plateforme.github.io).

**Comment by philippeBron** [comment]
Le tutoriel est en ligne à cette adresse : https://disic.github.io/rgaa_bibliotheques_javascript/tutoriels/index.html
j'ai suivi les conseil de @Tobino et ai repris l'ensemble du repo. A voir si il ne serait pas plus pertinent de ne conserver que la partie auto dans gh-pages.

**Comment by philippeBron** [comment]
Tutoriel mis en ligne : https://disic.github.io/rgaa_bibliotheques_javascript/tutoriels/index.html
